import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import PDFDocument from 'pdfkit';
import dbConnect from '@/lib/db';
import TaxRecord from '@/models/TaxRecord';
import User from '@/models/User';

export async function POST(req: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await req.json();
    const { recordId } = body;

    if (!recordId) {
      return NextResponse.json({ error: 'Record ID required' }, { status: 400 });
    }

    await dbConnect();

    const userId = (session.user as any).id;
    const taxRecord = await TaxRecord.findOne({ _id: recordId, userId });

    if (!taxRecord) {
      return NextResponse.json({ error: 'Tax record not found' }, { status: 404 });
    }

    const user = await User.findById(userId);

    // Generate PDF
    const doc = new PDFDocument({ margin: 50 });

    // Collect PDF data
    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));

    // Header
    doc.fontSize(20).font('Helvetica-Bold').text('TAXHUB NIGERIA', { align: 'center' });
    doc.fontSize(12).font('Helvetica').text('Tax Computation Report', { align: 'center' });
    doc.moveDown();

    // User Info
    doc.fontSize(10);
    doc.text(`Taxpayer: ${user.firstName} ${user.lastName}`);
    doc.text(`Email: ${user.email}`);
    doc.text(`Phone: ${user.phone}`);
    if (user.businessName) {
      doc.text(`Business: ${user.businessName}`);
    }
    doc.text(`Tier: ${user.tier}`);
    doc.moveDown();

    // Tax Details
    const taxTypeLabels: Record<string, string> = {
      paye: 'PERSONAL INCOME TAX (PAYE)',
      cit: 'COMPANY INCOME TAX (CIT)',
      vat: 'VALUE ADDED TAX (VAT)',
      wht: 'WITHHOLDING TAX',
      cgt: 'CAPITAL GAINS TAX',
    };

    doc.fontSize(14).font('Helvetica-Bold').text(taxTypeLabels[taxRecord.taxType] || taxRecord.taxType.toUpperCase(), { align: 'center' });
    doc.moveDown();

    doc.fontSize(11).font('Helvetica');
    doc.text(`Assessment Year: ${taxRecord.assessmentYear}`);
    if (taxRecord.periodStart && taxRecord.periodEnd) {
      doc.text(`Period: ${new Date(taxRecord.periodStart).toLocaleDateString()} - ${new Date(taxRecord.periodEnd).toLocaleDateString()}`);
    }
    doc.moveDown();

    // Financial Summary Table
    const tableTop = doc.y;
    const col1 = 50;
    const col2 = 200;
    const col3 = 350;

    doc.font('Helvetica-Bold').fontSize(10);
    doc.text('DESCRIPTION', col1, tableTop);
    doc.text('AMOUNT (₦)', col2, tableTop);
    doc.text('TAX (₦)', col3, tableTop);

    doc.moveTo(col1, tableTop + 15).lineTo(400, tableTop + 15).stroke();

    doc.font('Helvetica').fontSize(10);
    let y = tableTop + 25;

    doc.text('Total Income', col1, y);
    doc.text(taxRecord.totalIncome.toLocaleString(), col2, y);
    y += 20;

    if (taxRecord.totalExpenses > 0) {
      doc.text('Less: Allowable Expenses', col1, y);
      doc.text(taxRecord.totalExpenses.toLocaleString(), col2, y);
      y += 20;
    }

    doc.moveTo(col1, y).lineTo(400, y).stroke();
    y += 10;

    doc.font('Helvetica-Bold');
    doc.text('Taxable Income', col1, y);
    doc.text(taxRecord.taxableIncome.toLocaleString(), col2, y);
    y += 20;

    doc.text('Tax Liability', col1, y);
    doc.text(taxRecord.taxLiability.toLocaleString(), col2, y);
    y += 30;

    // Breakdown (if available)
    if (taxRecord.breakdown && Array.isArray(taxRecord.breakdown) && taxRecord.breakdown.length > 0) {
      doc.fontSize(11).text('Calculation Breakdown:', { underline: true });
      doc.moveDown();
      doc.fontSize(9);

      for (const item of taxRecord.breakdown) {
        const label = item.bracket || item.description || 'N/A';
        const rate = item.rate ? ` (${item.rate}%)` : '';
        const amount = item.amount ? `₦${item.amount.toLocaleString()}` : '-';
        const tax = item.tax ? `₦${item.tax.toLocaleString()}` : '-';

        doc.text(`${label}${rate}`, col1, y);
        doc.text(amount, col2, y);
        doc.text(tax, col3, y);
        y += 15;
      }
    }

    // Footer
    doc.fontSize(8);
    doc.text('This document was generated by TaxHub Nigeria', 50, 700, { align: 'center' });
    doc.text('For informational purposes. Consult a tax professional for official filings.', 50, 712, { align: 'center' });
    doc.text(`Generated on: ${new Date().toLocaleString()}`, 50, 724, { align: 'center' });

    doc.end();

    // Wait for PDF generation to complete
    await new Promise<void>((resolve) => doc.on('end', resolve));

    const pdfBuffer = Buffer.concat(chunks);

    return new NextResponse(pdfBuffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="TaxHub_${taxRecord.taxType}_${taxRecord.assessmentYear}.pdf"`,
      },
    });

  } catch (error: any) {
    console.error('PDF generation error:', error);
    return NextResponse.json({ error: 'Failed to generate PDF' }, { status: 500 });
  }
}