/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://vh6mpz5r6ba4fcrcsmkt7oayoa.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-exduhdvonzg6ric7fcybpv5pzi",
    "aws_cognito_identity_pool_id": "us-east-1:3f6a851a-8ecc-40cb-90f1-67e396d77b2e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_6N9hQgaQc",
    "aws_user_pools_web_client_id": "2pkeau9m9h2bcl2juvg2tejskm",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_content_delivery_bucket": "constructconnectweb-20260212102855-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d1k5ne2hvh4qew.cloudfront.net"
};


export default awsmobile;
